# Clash é…ç½®
# æ—¥æœŸï¼š2023.03.02
# é…ç½®ä½œè€…ï¼šhttps://t.me/iKeLee
# é€‚ç”¨ç‰ˆæœ¬ï¼šæ‰€æœ‰ä½¿ç”¨ Premium æ ¸å¿ƒçš„Clashç¨‹åº

port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: silent
external-controller: 127.0.0.1:9090

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
     - 119.29.29.29
  nameserver:
# è…¾è®¯é˜¿é‡ŒDoH2
     - https://1.12.12.12/dns-query
     - https://223.5.5.5/dns-query
  fallback:
# è…¾è®¯DoH2
     - https://120.53.53.53/dns-query

profile:
  tracing: true

# interval ä»£è¡¨é—´éš”æ—¶é—´ï¼Œå•ä½ä¸º sï¼›
# tolerance ä»£è¡¨å®¹å·®æ—¶é—´ï¼Œå•ä½ä¸º msï¼›
# ç”±äºåˆ†æµè§„åˆ™å¼•ç”¨äº† GitHub æ–‡ä»¶ï¼Œå¦‚æœä½ çš„æœ¬åœ°ç½‘ç»œæ— æ³•è®¿é—® GitHubï¼Œä½ å°†æ— æ³•è®© Clash æ­£å¸¸å·¥ä½œï¼›
# ä½ éœ€è¦å…ˆä½¿ç”¨ç¿»å¢™å·¥å…·è®©æœ¬åœ°ç½‘ç»œå‡ºå¢™ï¼Œå†å¯åŠ¨ Clash æ‰èƒ½æ­£å¸¸ä¸‹è½½åˆ†æµè§„åˆ™å¹¶æ­£å¸¸å¯åŠ¨ï¼Œå¾… Clash å¯åŠ¨æˆåŠŸå¹¶æ›´æ–°å®Œè®¢é˜…èµ„æºå’Œåˆ†æµè§„åˆ™ä¹‹åï¼Œæ–¹å¯å…³é—­ä½ ä¹‹å‰æ‰“å¼€çš„ç¿»å¢™å·¥å…·ï¼›
# è¯·ä½¿ç”¨èŠ‚ç‚¹è®¢é˜…è½¬æ¢æœåŠ¡å°†æœåŠ¡å•†çš„è®¢é˜…é“¾æ¥è½¬æ¢ä¸º Clash çš„è®¢é˜…ï¼Œå¹¶è¾“å‡ºä¸º Node List æ ¼å¼ï¼›
# è¯·ä½¿ç”¨èŠ‚ç‚¹è®¢é˜…è½¬æ¢å·¥å…·æä¾›çš„ä¿ç•™èŠ‚ç‚¹å’Œè¿‡æ»¤èŠ‚ç‚¹åŠŸèƒ½ï¼Œç”Ÿæˆä¸åŒåœ°åŒºçš„è®¢é˜…é“¾æ¥ï¼Œå¹¶å¡«å…¥ä¸‹æ–¹ proxy-providers åŒºåŸŸï¼›
# å…¶ä»–å†…å®¹å…·ä½“è§æ³¨é‡Šï¼›
# èŠ‚ç‚¹è®¢é˜…è½¬æ¢ç½‘å€ https://api.dler.io/
# å¦‚æœæœåŠ¡å•†ä¸æ”¯æŒä¸Šé¢çš„èŠ‚ç‚¹è®¢é˜…è½¬æ¢ï¼Œåˆ™ä½¿ç”¨å›½å†…çš„èŠ‚ç‚¹è®¢é˜…è½¬æ¢æœåŠ¡ï¼Œå¦‚ https://id9.cc/
# URLåœ¨çº¿ç¼–ç å·¥å…· https://www.urlencoder.org

# èŠ‚ç‚¹è®¢é˜…
# é»˜è®¤æ¯ä¸‰å°æ—¶æ›´æ–°ä¸€æ¬¡èŠ‚ç‚¹è®¢é˜…ï¼Œæ¯ 6s æ£€æµ‹ä¸€æ¬¡å¥åº·åº¦ã€‚

proxy-providers:
  é¦™æ¸¯èŠ‚ç‚¹:
    type: http
    path: ./Proxy/é¦™æ¸¯èŠ‚ç‚¹.yml
    url: https://api.dler.io/sub?target=clash&new_name=true&url=æ­¤å¤„æ›¿æ¢ä¸ºç»URLç¼–ç åçš„æœºåœºè®¢é˜…åœ°å€&insert=false&include=%5E(%3F%3D.*((%3Fi)%F0%9F%87%AD%F0%9F%87%B0%7C%E6%B8%AF%7C%E8%99%9A%E9%80%9A%7CHK%7CHong))(%3F!.*((%3Fi)%E5%9B%9E%E5%9B%BD%7C%E6%A0%A1%E5%9B%AD%7C%E6%B8%B8%E6%88%8F%7C%E6%95%99%E8%82%B2%7C%E4%B9%85%E8%99%9A%7C%E5%AE%98%E7%BD%91%7C%E5%AE%A2%E6%9C%8D%7C%E7%BD%91%E7%AB%99%7C%E7%BD%91%E5%9D%80%7C%E8%8E%B7%E5%8F%96%7C%E8%AE%A2%E9%98%85%7C%E6%B5%81%E9%87%8F%7C%E5%88%B0%E6%9C%9F%7C%E6%9C%BA%E5%9C%BA%7C%E4%B8%8B%E6%AC%A1%7C%E7%BE%A4%7C%5Cdx%7C%5Cd%E5%80%8D%7CGAME%7CTG)).*%24&filename=%E9%A6%99%E6%B8%AF%E8%8A%82%E7%82%B9.yml&emoji=false&list=true&udp=false&tfo=false&scv=false&fdn=false&sort=true
    interval: 10800
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 6

  å°æ¹¾èŠ‚ç‚¹:
    type: http
    path: ./Proxy/å°æ¹¾èŠ‚ç‚¹.yml
    url: https://api.dler.io/sub?target=clash&new_name=true&url=æ­¤å¤„æ›¿æ¢ä¸ºç»URLç¼–ç åçš„æœºåœºè®¢é˜…åœ°å€&insert=false&include=%5E(%3F%3D.*((%3Fi)%F0%9F%87%B9%F0%9F%87%BC%7C%E5%8F%B0%7CTW%7CTai))(%3F!.*((%3Fi)%E5%9B%9E%E5%9B%BD%7C%E6%A0%A1%E5%9B%AD%7C%E6%B8%B8%E6%88%8F%7C%E6%95%99%E8%82%B2%7C%E4%B9%85%E8%99%9A%7C%E5%AE%98%E7%BD%91%7C%E5%AE%A2%E6%9C%8D%7C%E7%BD%91%E7%AB%99%7C%E7%BD%91%E5%9D%80%7C%E8%8E%B7%E5%8F%96%7C%E8%AE%A2%E9%98%85%7C%E6%B5%81%E9%87%8F%7C%E5%88%B0%E6%9C%9F%7C%E6%9C%BA%E5%9C%BA%7C%E4%B8%8B%E6%AC%A1%7C%E7%BE%A4%7C%5Cdx%7C%5Cd%E5%80%8D%7CGAME%7CTG)).*%24&filename=%E5%8F%B0%E6%B9%BE%E8%8A%82%E7%82%B9.yml&emoji=false&list=true&udp=false&tfo=false&scv=false&fdn=false&sort=true
    interval: 10800
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 6

  æ—¥æœ¬èŠ‚ç‚¹:
    type: http
    path: ./Proxy/æ—¥æœ¬èŠ‚ç‚¹.yml
    url: https://api.dler.io/sub?target=clash&new_name=true&url=æ­¤å¤„æ›¿æ¢ä¸ºç»URLç¼–ç åçš„æœºåœºè®¢é˜…åœ°å€&insert=false&include=%5E(%3F%3D.*((%3Fi)%F0%9F%87%AF%F0%9F%87%B5%7C%E6%97%A5%7C%E5%B7%9D%E6%97%A5%7C%E4%B8%9C%E4%BA%AC%7C%E5%A4%A7%E9%98%AA%7C%E6%B3%89%E6%97%A5%7C%E5%9F%BC%E7%8E%89%7CJP%7CJapan))(%3F!.*((%3Fi)%E5%9B%9E%E5%9B%BD%7C%E6%A0%A1%E5%9B%AD%7C%E6%B8%B8%E6%88%8F%7C%E6%95%99%E8%82%B2%7C%E4%B9%85%E8%99%9A%7C%E5%AE%98%E7%BD%91%7C%E5%AE%A2%E6%9C%8D%7C%E7%BD%91%E7%AB%99%7C%E7%BD%91%E5%9D%80%7C%E8%8E%B7%E5%8F%96%7C%E8%AE%A2%E9%98%85%7C%E6%B5%81%E9%87%8F%7C%E5%88%B0%E6%9C%9F%7C%E6%9C%BA%E5%9C%BA%7C%E4%B8%8B%E6%AC%A1%7C%E7%BE%A4%7C%5Cdx%7C%5Cd%E5%80%8D%7CGAME%7CTG)).*%24&filename=%E6%97%A5%E6%9C%AC%E8%8A%82%E7%82%B9.yml&emoji=false&list=true&udp=false&tfo=false&scv=false&fdn=false&sort=true
    interval: 10800
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 6

  éŸ©å›½èŠ‚ç‚¹:
    type: http
    path: ./Proxy/éŸ©å›½èŠ‚ç‚¹.yml
    url: https://api.dler.io/sub?target=clash&new_name=true&url=æ­¤å¤„æ›¿æ¢ä¸ºç»URLç¼–ç åçš„æœºåœºè®¢é˜…åœ°å€&insert=false&include=%5E(%3F%3D.*((%3Fi)%F0%9F%87%B0%F0%9F%87%B7%7C%E9%9F%A9%7C%E9%9F%93%7C%E9%A6%96%E5%B0%94%7CKR%7CKorea))(%3F!.*((%3Fi)%E5%9B%9E%E5%9B%BD%7C%E6%A0%A1%E5%9B%AD%7C%E6%B8%B8%E6%88%8F%7C%E6%95%99%E8%82%B2%7C%E4%B9%85%E8%99%9A%7C%E5%AE%98%E7%BD%91%7C%E5%AE%A2%E6%9C%8D%7C%E7%BD%91%E7%AB%99%7C%E7%BD%91%E5%9D%80%7C%E8%8E%B7%E5%8F%96%7C%E8%AE%A2%E9%98%85%7C%E6%B5%81%E9%87%8F%7C%E5%88%B0%E6%9C%9F%7C%E6%9C%BA%E5%9C%BA%7C%E4%B8%8B%E6%AC%A1%7C%E7%BE%A4%7C%5Cdx%7C%5Cd%E5%80%8D%7CGAME%7CTG)).*%24&filename=%E9%9F%A9%E5%9B%BD%E8%8A%82%E7%82%B9.yml&emoji=false&list=true&udp=false&tfo=false&scv=false&fdn=false&sort=true
    interval: 10800
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 6

  ç¾å›½èŠ‚ç‚¹:
    type: http
    path: ./Proxy/ç¾å›½èŠ‚ç‚¹.yml
    url: https://api.dler.io/sub?target=clash&new_name=true&url=æ­¤å¤„æ›¿æ¢ä¸ºç»URLç¼–ç åçš„æœºåœºè®¢é˜…åœ°å€&insert=false&include=%5E(%3F%3D.*((%3Fi)%F0%9F%87%BA%F0%9F%87%B8%7C%E7%BE%8E%7C%E6%B3%A2%E7%89%B9%E5%85%B0%7C%E8%BE%BE%E6%8B%89%E6%96%AF%7C%E4%BF%84%E5%8B%92%E5%86%88%7C%E5%87%A4%E5%87%B0%E5%9F%8E%7C%E8%B4%B9%E5%88%A9%E8%92%99%7C%E7%A1%85%E8%B0%B7%7C%E6%8B%89%E6%96%AF%E7%BB%B4%E5%8A%A0%E6%96%AF%7C%E6%B4%9B%E6%9D%89%E7%9F%B6%7C%E5%9C%A3%E4%BD%95%E5%A1%9E%7C%E5%9C%A3%E5%85%8B%E6%8B%89%E6%8B%89%7C%E8%A5%BF%E9%9B%85%E5%9B%BE%7C%E8%8A%9D%E5%8A%A0%E5%93%A5%7CUS%7CUnitedStates))(%3F!.*((%3Fi)%E5%9B%9E%E5%9B%BD%7C%E6%A0%A1%E5%9B%AD%7C%E6%B8%B8%E6%88%8F%7C%E6%95%99%E8%82%B2%7C%E4%B9%85%E8%99%9A%7C%E5%AE%98%E7%BD%91%7C%E5%AE%A2%E6%9C%8D%7C%E7%BD%91%E7%AB%99%7C%E7%BD%91%E5%9D%80%7C%E8%8E%B7%E5%8F%96%7C%E8%AE%A2%E9%98%85%7C%E6%B5%81%E9%87%8F%7C%E5%88%B0%E6%9C%9F%7C%E6%9C%BA%E5%9C%BA%7C%E4%B8%8B%E6%AC%A1%7C%E7%BE%A4%7C%5Cdx%7C%5Cd%E5%80%8D%7CGAME%7CTG)).*%24&filename=%E7%BE%8E%E5%9B%BD%E8%8A%82%E7%82%B9.yml&emoji=false&list=true&udp=false&tfo=false&scv=false&fdn=false&sort=true
    interval: 10800
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 6

  æ–°åŠ å¡èŠ‚ç‚¹:
    type: http
    path: ./Proxy/æ–°åŠ å¡èŠ‚ç‚¹.yml
    url: https://api.dler.io/sub?target=clash&new_name=true&url=æ­¤å¤„æ›¿æ¢ä¸ºç»URLç¼–ç åçš„æœºåœºè®¢é˜…åœ°å€&insert=false&include=%5E(%3F%3D.*((%3Fi)%F0%9F%87%B8%F0%9F%87%AC%7C%E6%96%B0%E5%8A%A0%E5%9D%A1%7C%E7%8B%AE%7CSG%7CSingapore))(%3F!.*((%3Fi)%E5%9B%9E%E5%9B%BD%7C%E6%A0%A1%E5%9B%AD%7C%E6%B8%B8%E6%88%8F%7C%E6%95%99%E8%82%B2%7C%E4%B9%85%E8%99%9A%7C%E5%AE%98%E7%BD%91%7C%E5%AE%A2%E6%9C%8D%7C%E7%BD%91%E7%AB%99%7C%E7%BD%91%E5%9D%80%7C%E8%8E%B7%E5%8F%96%7C%E8%AE%A2%E9%98%85%7C%E6%B5%81%E9%87%8F%7C%E5%88%B0%E6%9C%9F%7C%E6%9C%BA%E5%9C%BA%7C%E4%B8%8B%E6%AC%A1%7C%E7%BE%A4%7C%5Cdx%7C%5Cd%E5%80%8D%7CGAME%7CTG)).*%24&filename=%E6%96%B0%E5%8A%A0%E5%9D%A1%E8%8A%82%E7%82%B9.yml&emoji=false&list=true&udp=false&tfo=false&scv=false&fdn=false&sort=true
    interval: 10800
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 6

  å…¨çƒèŠ‚ç‚¹:
    type: http
    path: ./Proxy/å…¨çƒèŠ‚ç‚¹.yml
    url: https://api.dler.io/sub?target=clash&new_name=true&url=æ­¤å¤„æ›¿æ¢ä¸ºç»URLç¼–ç åçš„æœºåœºè®¢é˜…åœ°å€&insert=false&include=%5E(%3F%3D.*(.*))(%3F!.*((%3Fi)%E4%B9%85%E8%99%9A%7C%E5%AE%98%E7%BD%91%7C%E5%AE%A2%E6%9C%8D%7C%E7%BD%91%E7%AB%99%7C%E7%BD%91%E5%9D%80%7C%E8%8E%B7%E5%8F%96%7C%E8%AE%A2%E9%98%85%7C%E6%B5%81%E9%87%8F%7C%E5%88%B0%E6%9C%9F%7C%E6%9C%BA%E5%9C%BA%7C%E4%B8%8B%E6%AC%A1%7C%E7%BE%A4%7CTG)).*%24&filename=%E5%85%A8%E7%90%83%E8%8A%82%E7%82%B9.yml&emoji=false&list=true&udp=false&tfo=false&scv=false&fdn=false&sort=true
    interval: 10800
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 6

proxy-groups:
  - name: æ‰‹åŠ¨èŠ‚ç‚¹é€‰æ‹©
    type: select
    disable-udp: false
    use:
      - å…¨çƒèŠ‚ç‚¹
    proxies:
      - DIRECT

  - name: åœ°åŒºé€‰æ‹©
    type: select
    proxies:
      - é¦™æ¸¯ç­–ç•¥
      - å°æ¹¾ç­–ç•¥
      - æ—¥æœ¬ç­–ç•¥
      - éŸ©å›½ç­–ç•¥
      - ç¾å›½ç­–ç•¥
      - æ–°åŠ å¡ç­–ç•¥

  - name: å¢ƒå¤–æ¸¸æˆCDNä¸‹è½½
    type: select
    proxies:
      - é¦™æ¸¯ç­–ç•¥
      - å°æ¹¾ç­–ç•¥
      - æ—¥æœ¬ç­–ç•¥
      - éŸ©å›½ç­–ç•¥
      - ç¾å›½ç­–ç•¥
      - æ–°åŠ å¡ç­–ç•¥
      - DIRECT

  - name: App Store
    type: select
    proxies:
      - åœ°åŒºé€‰æ‹©
      - DIRECT

  - name: Apple ID
    type: select
    proxies:
      - åœ°åŒºé€‰æ‹©
      - DIRECT

  - name: TestFlight
    type: select
    proxies:
      - åœ°åŒºé€‰æ‹©
      - DIRECT

  - name: Microsoft
    type: select
    proxies:
      - åœ°åŒºé€‰æ‹©
      - DIRECT

  - name: TikTok
    type: select
    proxies:
      - é¦™æ¸¯ç­–ç•¥
      - å°æ¹¾ç­–ç•¥
      - æ—¥æœ¬ç­–ç•¥
      - éŸ©å›½ç­–ç•¥
      - ç¾å›½ç­–ç•¥
      - æ–°åŠ å¡ç­–ç•¥

  - name: Telegram
    type: select
    proxies:
      - é¦™æ¸¯ç­–ç•¥
      - å°æ¹¾ç­–ç•¥
      - æ—¥æœ¬ç­–ç•¥
      - éŸ©å›½ç­–ç•¥
      - ç¾å›½ç­–ç•¥
      - æ–°åŠ å¡ç­–ç•¥

  - name: Netflix
    type: select
    proxies:
      - é¦™æ¸¯ç­–ç•¥
      - å°æ¹¾ç­–ç•¥
      - æ—¥æœ¬ç­–ç•¥
      - éŸ©å›½ç­–ç•¥
      - ç¾å›½ç­–ç•¥
      - æ–°åŠ å¡ç­–ç•¥

  - name: Speedtest
    type: select
    disable-udp: false
    use:
      - å…¨çƒèŠ‚ç‚¹
    proxies:
      - DIRECT

  - name: é¦™æ¸¯ç­–ç•¥
    type: select
    proxies:
      - â±é¦™æ¸¯å»¶æ—¶ä¼˜é€‰ç­–ç•¥ç»„
      - ğŸš¥é¦™æ¸¯æ•…éšœè½¬ç§»ç­–ç•¥ç»„
      - ğŸ›é¦™æ¸¯è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„

  - name: å°æ¹¾ç­–ç•¥
    type: select
    proxies:
      - â±å°æ¹¾å»¶æ—¶ä¼˜é€‰ç­–ç•¥ç»„
      - ğŸš¥å°æ¹¾æ•…éšœè½¬ç§»ç­–ç•¥ç»„
      - ğŸ›å°æ¹¾è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„

  - name: æ—¥æœ¬ç­–ç•¥
    type: select
    proxies:
      - â±æ—¥æœ¬å»¶æ—¶ä¼˜é€‰ç­–ç•¥ç»„
      - ğŸš¥æ—¥æœ¬æ•…éšœè½¬ç§»ç­–ç•¥ç»„
      - ğŸ›æ—¥æœ¬è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„

  - name: éŸ©å›½ç­–ç•¥
    type: select
    proxies:
      - â±éŸ©å›½å»¶æ—¶ä¼˜é€‰ç­–ç•¥ç»„
      - ğŸš¥éŸ©å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„
      - ğŸ›éŸ©å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„

  - name: ç¾å›½ç­–ç•¥
    type: select
    proxies:
      - â±ç¾å›½å»¶æ—¶ä¼˜é€‰ç­–ç•¥ç»„
      - ğŸš¥ç¾å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„
      - ğŸ›ç¾å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„

  - name: æ–°åŠ å¡ç­–ç•¥
    type: select
    proxies:
      - â±æ–°åŠ å¡å»¶æ—¶ä¼˜é€‰ç­–ç•¥ç»„
      - ğŸš¥æ–°åŠ å¡æ•…éšœè½¬ç§»ç­–ç•¥ç»„
      - ğŸ›æ–°åŠ å¡è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„

  - name: å…œåº•ç­–ç•¥
    type: select
    proxies:
      - åœ°åŒºé€‰æ‹©
      - æ‰‹åŠ¨èŠ‚ç‚¹é€‰æ‹©
      - DIRECT

# å»¶æ—¶ä¼˜é€‰
# url-test çš„å®¹å·®å‚æ•°æœªå¼€å¯æ—¶é»˜è®¤ä¸º 0ms
  - name: â±é¦™æ¸¯å»¶æ—¶ä¼˜é€‰ç­–ç•¥ç»„
    type: url-test
    tolerance: 20
    lazy: false
    disable-udp: false
    use:
      - é¦™æ¸¯èŠ‚ç‚¹

  - name: â±å°æ¹¾å»¶æ—¶ä¼˜é€‰ç­–ç•¥ç»„
    type: url-test
    tolerance: 20
    lazy: false
    disable-udp: false
    use:
      - å°æ¹¾èŠ‚ç‚¹

  - name: â±æ—¥æœ¬å»¶æ—¶ä¼˜é€‰ç­–ç•¥ç»„
    type: url-test
    tolerance: 20
    lazy: false
    disable-udp: false
    use:
      - æ—¥æœ¬èŠ‚ç‚¹

  - name: â±éŸ©å›½å»¶æ—¶ä¼˜é€‰ç­–ç•¥ç»„
    type: url-test
    tolerance: 20
    lazy: false
    disable-udp: false
    use:
      - éŸ©å›½èŠ‚ç‚¹

  - name: â±ç¾å›½å»¶æ—¶ä¼˜é€‰ç­–ç•¥ç»„
    type: url-test
    tolerance: 20
    lazy: false
    disable-udp: false
    use:
      - ç¾å›½èŠ‚ç‚¹

  - name: â±æ–°åŠ å¡å»¶æ—¶ä¼˜é€‰ç­–ç•¥ç»„
    type: url-test
    tolerance: 20
    lazy: false
    disable-udp: false
    use:
      - æ–°åŠ å¡èŠ‚ç‚¹

# æ•…éšœè½¬ç§»
  - name: ğŸš¥é¦™æ¸¯æ•…éšœè½¬ç§»ç­–ç•¥ç»„
    type: fallback
    lazy: false
    disable-udp: false
    use:
      - é¦™æ¸¯èŠ‚ç‚¹

  - name: ğŸš¥å°æ¹¾æ•…éšœè½¬ç§»ç­–ç•¥ç»„
    type: fallback
    lazy: false
    disable-udp: false
    use:
      - å°æ¹¾èŠ‚ç‚¹

  - name: ğŸš¥æ—¥æœ¬æ•…éšœè½¬ç§»ç­–ç•¥ç»„
    type: fallback
    lazy: false
    disable-udp: false
    use:
      - æ—¥æœ¬èŠ‚ç‚¹

  - name: ğŸš¥éŸ©å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„
    type: fallback
    lazy: false
    disable-udp: false
    use:
      - éŸ©å›½èŠ‚ç‚¹

  - name: ğŸš¥ç¾å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„
    type: fallback
    lazy: false
    disable-udp: false
    use:
      - ç¾å›½èŠ‚ç‚¹

  - name: ğŸš¥æ–°åŠ å¡æ•…éšœè½¬ç§»ç­–ç•¥ç»„
    type: fallback
    lazy: false
    disable-udp: false
    use:
      - æ–°åŠ å¡èŠ‚ç‚¹

# è´Ÿè½½å‡è¡¡
  - name: ğŸ›é¦™æ¸¯è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„
    type: load-balance
    lazy: false
    disable-udp: false
    strategy: consistent-hashing
    use:
      - é¦™æ¸¯èŠ‚ç‚¹

  - name: ğŸ›å°æ¹¾è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„
    type: load-balance
    lazy: false
    disable-udp: false
    strategy: consistent-hashing
    use:
      - å°æ¹¾èŠ‚ç‚¹

  - name: ğŸ›æ—¥æœ¬è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„
    type: load-balance
    lazy: false
    disable-udp: false
    strategy: consistent-hashing
    use:
      - æ—¥æœ¬èŠ‚ç‚¹

  - name: ğŸ›éŸ©å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„
    type: load-balance
    lazy: false
    disable-udp: false
    strategy: consistent-hashing
    use:
      - éŸ©å›½èŠ‚ç‚¹

  - name: ğŸ›ç¾å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„
    type: load-balance
    lazy: false
    disable-udp: false
    strategy: consistent-hashing
    use:
      - ç¾å›½èŠ‚ç‚¹

  - name: ğŸ›æ–°åŠ å¡è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„
    type: load-balance
    lazy: false
    disable-udp: false
    strategy: consistent-hashing
    use:
      - æ–°åŠ å¡èŠ‚ç‚¹

# åˆ†æµè§„åˆ™è®¢é˜…
# é»˜è®¤æ¯äºŒåå››å°æ—¶æ›´æ–°ä¸€æ¬¡åˆ†æµè§„åˆ™
rule-providers:
  Lan:
    type: http
    behavior: classical
    path: ./RuleSet/Lan.yaml
    url: https://gitlab.com/lodepuly/proxy_tool_resources/-/raw/master/rule/Clash/Lan/Lan.yaml
    interval: 10800

  Direct:
    type: http
    behavior: classical
    path: ./RuleSet/Direct.yaml
    url: https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Clash/Rule/Direct.yaml
    interval: 10800

  Proxy:
    type: http
    behavior: classical
    path: ./RuleSet/Proxy.yaml
    url: https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Clash/Rule/Proxy.yaml
    interval: 10800

  ChineseGameDownload:
    type: http
    behavior: classical
    path: ./RuleSet/ChineseGameDownload.yaml
    url: https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Clash/Rule/ChineseGameDownload.yaml
    interval: 10800

  InternationalGameDownload:
    type: http
    behavior: classical
    path: ./RuleSet/InternationalGameDownload.yaml
    url: https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Clash/Rule/InternationalGameDownload.yaml
    interval: 10800

  TikTok:
    type: http
    behavior: classical
    path: ./RuleSet/TikTok.yaml
    url: https://gitlab.com/lodepuly/proxy_tool_resources/-/raw/master/rule/Clash/TikTok/TikTok.yaml
    interval: 10800

  Game:
    type: http
    behavior: classical
    path: ./RuleSet/Game.yaml
    url: https://gitlab.com/lodepuly/proxy_tool_resources/-/raw/master/rule/Clash/Game/Game.yaml
    interval: 10800

  Steam:
    type: http
    behavior: classical
    path: ./RuleSet/Steam.yaml
    url: https://gitlab.com/lodepuly/proxy_tool_resources/-/raw/master/rule/Clash/Steam/Steam.yaml
    interval: 10800

  Netflix:
    type: http
    behavior: classical
    path: ./RuleSet/Netflix.yaml
    url: https://gitlab.com/lodepuly/proxy_tool_resources/-/raw/master/rule/Clash/Netflix/Netflix.yaml
    interval: 10800

  iCloudChina:
    type: http
    behavior: classical
    path: ./RuleSet/iCloudChina.yaml
    url: https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Clash/Rule/iCloudChina.yaml
    interval: 10800

  ApplePushNotificationService:
    type: http
    behavior: classical
    path: ./RuleSet/AppleID.yaml
    url: https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Clash/Rule/ApplePushNotificationService.yaml
    interval: 10800

  AppleSoftwareUpdates:
    type: http
    behavior: classical
    path: ./RuleSet/AppleID.yaml
    url: https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Clash/Rule/AppleSoftwareUpdates.yaml
    interval: 10800

  AppleID:
    type: http
    behavior: classical
    path: ./RuleSet/AppleID.yaml
    url: https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Clash/Rule/AppleID.yaml
    interval: 10800

  AppStore:
    type: http
    behavior: classical
    path: ./RuleSet/AppStore.yaml
    url: https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Clash/Rule/AppStore.yaml
    interval: 10800

  TestFlight:
    type: http
    behavior: classical
    path: ./RuleSet/TestFlight.yaml
    url: https://gitlab.com/lodepuly/proxy_tool_resources/-/raw/master/rule/Clash/TestFlight/TestFlight.yaml
    interval: 10800

  Speedtest:
    type: http
    behavior: classical
    path: ./RuleSet/Speedtest.yaml
    url: https://gitlab.com/lodepuly/proxy_tool_resources/-/raw/master/rule/Clash/Speedtest/Speedtest.yaml
    interval: 10800

  Bing:
    type: http
    behavior: classical
    path: ./RuleSet/Bing.yaml
    url: https://gitlab.com/lodepuly/proxy_tool_resources/-/raw/master/rule/Clash/Bing/Bing.yaml
    interval: 10800

  Microsoft:
    type: http
    behavior: classical
    path: ./RuleSet/Microsoft.yaml
    url: https://gitlab.com/lodepuly/proxy_tool_resources/-/raw/master/rule/Clash/Microsoft/Microsoft.yaml
    interval: 10800

  Google:
    type: http
    behavior: classical
    path: ./RuleSet/Google.yaml
    url: https://gitlab.com/lodepuly/proxy_tool_resources/-/raw/master/rule/Clash/Google/Google.yaml
    interval: 10800

  Telegram:
    type: http
    behavior: classical
    path: ./RuleSet/Telegram.yaml
    url: https://gitlab.com/lodepuly/proxy_tool_resources/-/raw/master/rule/Clash/Telegram/Telegram.yaml
    interval: 10800

  ESET_Activation_Service:
    type: http
    behavior: classical
    path: ./RuleSet/ESET_Activation_Service.yaml
    url: https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Clash/Rule/ESET_Activation_Service.yaml
    interval: 10800

# åˆ†æµè§„åˆ™
rules:
  - RULE-SET,Lan,DIRECT
  - RULE-SET,Direct,DIRECT
  - RULE-SET,Proxy,åœ°åŒºé€‰æ‹©
  - RULE-SET,ChineseGameDownload,DIRECT
  - RULE-SET,InternationalGameDownload,å¢ƒå¤–æ¸¸æˆCDNä¸‹è½½
  - RULE-SET,TikTok,TikTok
  - RULE-SET,Game,æ‰‹åŠ¨èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,Steam,åœ°åŒºé€‰æ‹©
  - RULE-SET,Netflix,Netflix
  - RULE-SET,TestFlight,TestFlight
  - RULE-SET,iCloudChina,DIRECT
  - RULE-SET,ApplePushNotificationService,DIRECT
  - RULE-SET,AppleSoftwareUpdates,DIRECT
  - RULE-SET,AppleID,Apple ID
  - RULE-SET,AppStore,App Store
  - RULE-SET,Speedtest,Speedtest
  - RULE-SET,Bing,åœ°åŒºé€‰æ‹©
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Google,åœ°åŒºé€‰æ‹©
  - RULE-SET,Telegram,Telegram
  - RULE-SET,ESET_Activation_Service,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,å…œåº•ç­–ç•¥